begin
    execute immediate 'drop table oj_mcp_allowed_origins';
exception
   when others then
       null;
end;
/

begin
    execute immediate 'drop table oj_mcp_task_states';
exception
   when others then
       null;
end;
/

begin
    execute immediate 'drop table oj_mcp_tools_annotations';
exception
   when others then
       null;
end;
/

begin
    execute immediate 'drop table oj_mcp_tools_extras';
exception
   when others then
       null;
end;
/

begin
    execute immediate 'drop table oj_mcp_ui_permissions';
exception
   when others then
       null;
end;
/

begin
    execute immediate 'drop table oj_mcp_ui_csp_domains';
exception
   when others then
       null;
end;
/

begin
    execute immediate 'drop table oj_mcp_ui_resources';
exception
   when others then
       null;
end;
/

/*
 * Exact Origin values allowed to call the MCP endpoint from a browser context.
 * Requests without an Origin header are intended for native MCP clients and do
 * not require an entry. An empty table rejects every request that has Origin.
 */
create table oj_mcp_allowed_origins (
    origin varchar2(1000 char)
        constraint pk_oj_mcp_allowed_origins primary key
);

comment on table oj_mcp_allowed_origins is
    'Exact browser Origin values allowed to call the MCP HTTP endpoint';

/*
 * Durable state for the io.modelcontextprotocol/tasks extension.
 */
create table oj_mcp_task_states (
    task_id               varchar2(64 char)
        constraint pk_oj_mcp_task_states primary key,
    owner_name            varchar2(255 char) not null,
    execution_schema      varchar2(128 char) not null,
    tool_name             varchar2(128 char) not null,
    arguments_json        clob,
    status                varchar2(20 char) not null,
    status_message        varchar2(4000 char),
    result_json           clob,
    error_json            clob,
    created_at            timestamp with time zone not null,
    last_updated_at       timestamp with time zone not null,
    ttl_ms                number,
    poll_interval_ms      number,
    cancel_requested      number(1) default 0 not null,
    ords_pattern          varchar2(255 char) not null,
    ords_module_name      varchar2(255 char) not null,
    apex_app_id           number not null,
    apex_page_id          number not null,
    ras_config_pkg        varchar2(128 char),
    aq_msgid              raw(16),
    constraint ck_oj_mcp_task_states_status check (
        status in ('working', 'input_required', 'completed', 'cancelled', 'failed')
    ),
    constraint ck_oj_mcp_task_states_cancel check (cancel_requested in (0, 1)),
    constraint ck_oj_mcp_task_states_args_json check (arguments_json is json),
    constraint ck_oj_mcp_task_states_result_json check (result_json is json),
    constraint ck_oj_mcp_task_states_error_json check (error_json is json)
);

create index ix_oj_mcp_task_states_owner on oj_mcp_task_states(owner_name, task_id);

comment on table oj_mcp_task_states is
    'Durable task states for the MCP io.modelcontextprotocol/tasks extension';

/*
 * Table for storing UI resources.
 *
 * Generated by Claude Sonnet 4.6 from the typescript interface in the official documentation.
 * 
 * SEP-1865: MCP Apps: Interactive User Interfaces for MCP
 * Specification
 * UI Resource Format
 * https://github.com/modelcontextprotocol/ext-apps/blob/main/specification/2026-01-26/apps.mdx#ui-resource-format
 *
 * Design points reported by Claude Sonnet 4.6:
 * - prefersBorder is a tristate value (true/false/omitted), represented as NUMBER(1) NULL
 * - The 4 array-type fields such as connectDomains are normalized into OJ_MCP_UI_CSP_DOMAINS, with the domain_type column used to distinguish each type
 * - Each field in permissions is typed as an object ({}), but acts as a boolean flag in practice, so it is stored as a flat NUMBER(1) column in OJ_MCP_UI_PERMISSIONS
 * - ON DELETE CASCADE automatically removes related records when a resource is delete dboolean type is translated into Oracle's NUMBER, 0 = false, 1 = true
 */
create table oj_mcp_ui_resources (
    id          number generated by default on null as identity
                constraint pk_oj_mcp_ui_resources primary key,
    uri         varchar2(1000 char) not null,
    name        varchar2(255  char) not null,
    description varchar2(4000 char),
    mime_type   varchar2(255  char) default 'text/html;profile=mcp-app' not null,
    text        clob,
    prefers_border  number(1),
    domain          varchar2(1000 char),
    coding_hint     clob,
    created_by      varchar2(255 char) not null,
    created_at      timestamp          not null,
    updated_by      varchar2(255 char) not null,
    updated_at      timestamp          not null,
    constraint uq_oj_mcp_ui_resources_uri unique (uri),
    constraint ck_oj_mcp_ui_resources_prefers_border check (prefers_border in (0, 1))
);

comment on table  oj_mcp_ui_resources                is 'MCP UI Resources (SEP-1865 UIResource)';
comment on column oj_mcp_ui_resources.uri            is 'Unique resource URI (ui:// scheme)';
comment on column oj_mcp_ui_resources.mime_type      is 'MIME type; typically text/html;profile=mcp-app';
comment on column oj_mcp_ui_resources.prefers_border is '_meta.ui.prefersBorder: 1=true, 0=false, NULL=host default';
comment on column oj_mcp_ui_resources.domain         is '_meta.ui.domain: dedicated sandbox origin';
comment on column oj_mcp_ui_resources.coding_hint    is 'Guidelines the LLM Should Refer to When Generating UI Resource bundle';

create table oj_mcp_ui_csp_domains (
    id          number generated by default on null as identity
                constraint pk_oj_mcp_ui_csp_domains primary key,
    resource_id number              not null,
    domain_type varchar2(20   char) not null,
    domain      varchar2(1000 char) not null,
    created_by  varchar2(255 char)  not null,
    created_at  timestamp           not null,
    updated_by  varchar2(255 char)  not null,
    updated_at  timestamp           not null,
    constraint fk_oj_mcp_ui_csp_resource
        foreign key (resource_id) references oj_mcp_ui_resources(id) on delete cascade,
    constraint ck_oj_mcp_ui_csp_domain_type
        check (domain_type in ('CONNECT', 'RESOURCE', 'FRAME', 'BASE_URI'))
);

comment on table  oj_mcp_ui_csp_domains             is 'CSP domain lists per UI resource';
comment on column oj_mcp_ui_csp_domains.domain_type is 'CONNECT=connectDomains, RESOURCE=resourceDomains, FRAME=frameDomains, BASE_URI=baseUriDomains';

create index ix_oj_mcp_ui_csp_resource_id on oj_mcp_ui_csp_domains(resource_id);

create table oj_mcp_ui_permissions (
    resource_id          number not null,
    perm_camera          number(1) default 0 not null,
    perm_microphone      number(1) default 0 not null,
    perm_geolocation     number(1) default 0 not null,
    perm_clipboard_write number(1) default 0 not null,
    created_by           varchar2(255 char)  not null,
    created_at           timestamp           not null,
    updated_by           varchar2(255 char)  not null,
    updated_at           timestamp           not null,
    constraint pk_oj_mcp_ui_permissions primary key (resource_id),
    constraint fk_oj_mcp_ui_perm_resource
        foreign key (resource_id) references oj_mcp_ui_resources(id) on delete cascade,
    constraint ck_oj_mcp_ui_perm_camera
        check (perm_camera in (0, 1)),
    constraint ck_oj_mcp_ui_perm_microphone
        check (perm_microphone in (0, 1)),
    constraint ck_oj_mcp_ui_perm_geolocation
        check (perm_geolocation in (0, 1)),
    constraint ck_oj_mcp_ui_perm_clipboard_write
        check (perm_clipboard_write in (0, 1))
);

comment on table  oj_mcp_ui_permissions                     is 'Sandbox permission requests per UI resource';
comment on column oj_mcp_ui_permissions.perm_camera         is 'permissions.camera: 1=requested';
comment on column oj_mcp_ui_permissions.perm_microphone     is 'permissions.microphone: 1=requested';
comment on column oj_mcp_ui_permissions.perm_geolocation    is 'permissions.geolocation: 1=requested';
comment on column oj_mcp_ui_permissions.perm_clipboard_write is 'permissions.clipboardWrite: 1=requested';

/*
 * Extend UC_AI_TOOLS to have resource _meta data and output_schema.
 */
create table oj_mcp_tools_extras (
    tool_id       number not null, 
    resource_id   number,
    output_schema clob,
    visibility    number,
    resource_consumer_group varchar2(32),
    coding_hint   clob,
    task_enabled  number(1) default 0 not null,
    task_ttl_ms   number default 3600000,
    task_poll_interval_ms number default 1000,
    constraint oj_mcp_tools_extras_pk primary key ("TOOL_ID")
);

comment on table  oj_mcp_tools_extras               is 'Additional Information for Associating a UIResource with an MCP Tool';
comment on column oj_mcp_tools_extras.tool_id       is 'id of tool stored in UC_AI_TOOLS';
comment on column oj_mcp_tools_extras.output_schema is 'JSON Schema for Defining Structured Output';
comment on column oj_mcp_tools_extras.visibility    is 'null = default, 1 = model only, 2 = app only, 3 = model and app';
comment on column oj_mcp_tools_extras.coding_hint   is 'Guidelines the LLM Should Refer to When Generating PL/SQL Functions';
comment on column oj_mcp_tools_extras.task_enabled  is '1 enables MCP Task execution when the client supports the Tasks extension';
comment on column oj_mcp_tools_extras.task_ttl_ms   is 'Task lifetime in milliseconds; NULL means unlimited';
comment on column oj_mcp_tools_extras.task_poll_interval_ms is 'Suggested client polling interval in milliseconds';

alter table oj_mcp_tools_extras add constraint ck_oj_mcp_tools_extras_task
check (task_enabled in (0, 1));

alter table oj_mcp_tools_extras add constraint ck_oj_mcp_tools_extras_task_ttl
check (
    task_ttl_ms is null
    or (task_ttl_ms >= 0 and task_ttl_ms = trunc(task_ttl_ms))
);

alter table oj_mcp_tools_extras add constraint ck_oj_mcp_tools_extras_task_poll
check (
    task_poll_interval_ms is null
    or (task_poll_interval_ms >= 0 and task_poll_interval_ms = trunc(task_poll_interval_ms))
);

alter table oj_mcp_tools_extras add constraint oj_mcp_tools_extras_tool_id_fk foreign key ("TOOL_ID")
references uc_ai_tools ("ID") on delete cascade enable;

alter table oj_mcp_tools_extras add constraint oj_mcp_tools_extras_resource_id_fk foreign key ("RESOURCE_ID")
references oj_mcp_ui_resources ("ID") on delete cascade enable;

/*
 * Tool annotations
 */
create table oj_mcp_tools_annotations (
    tool_id          number not null,
    title            varchar2(128),
    read_only_hint   number(1) default 0 not null,
    destructive_hint number(1) default 1 not null,
    idempotent_hint  number(1) default 0 not null,
    open_world_hint  number(1) default 1 not null,
    constraint oj_mcp_tools_annotations_pk primary key ("TOOL_ID")
);

comment on table  oj_mcp_tools_annotations                  is 'Annotation flags of MCP Tool';
comment on column oj_mcp_tools_annotations.tool_id          is 'id of tool stored in UC_AI_TOOLS';
comment on column oj_mcp_tools_annotations.title            is 'title of the annotation of MCP Tool';
comment on column oj_mcp_tools_annotations.read_only_hint   is 'tool is read only, default = false';
comment on column oj_mcp_tools_annotations.destructive_hint is 'tool is destructive, default = true';
comment on column oj_mcp_tools_annotations.idempotent_hint  is 'tool is idempotent, default = false';
comment on column oj_mcp_tools_annotations.open_world_hint  is 'tool is publicly accessible, default = true';

alter table oj_mcp_tools_annotations add constraint oj_mcp_tools_annotations_tool_id_fk foreign key ("TOOL_ID")
references uc_ai_tools ("ID") on delete cascade enable;

/*
 * Add definitions for resources and output_schema to UC_AI_TOOLS.
 */
create or replace view oj_mcp_uc_ai_tools as
select
    t.id                   id,
    t.code                 code,
    t.description          description,
    t.active               active,
    t.response_schema      response_schema,
    t.version              version,
    t.function_call        function_call,
    t.authorization_schema authorization_schema,
    t.created_by           created_by,
    t.created_at           created_at,
    t.updated_by           updated_by,
    t.updated_at           updated_at,
    e.resource_id          resource_id,
    e.output_schema        output_schema,
    e.resource_consumer_group resource_consumer_group,
    e.coding_hint          coding_hint,
    e.visibility           visibility,
    e.task_enabled         task_enabled,
    e.task_ttl_ms          task_ttl_ms,
    e.task_poll_interval_ms task_poll_interval_ms
from
    uc_ai_tools t left outer join oj_mcp_tools_extras e
    on t.id = e.tool_id
;
