begin
    execute immediate 'drop table oj_mcp_tools_extras';
exception
   when others then
       null;
end;
/

begin
    execute immediate 'drop table oj_mcp_app_resources';
exception
   when others then
       null;
end;
/

/*
 * Resouce definitions for MCP Apps.
 * Referenced by resources/list and resources/read.
 */ 
create table oj_mcp_app_resources (
    id              number generated by default on null as identity
                    constraint oj_mcp_app_resources_id_pk primary key,
    resource_name   varchar2(80  char),
    resource_uri    varchar2(255 char) not null,
    mime_type       varchar2(80  char) default 'text/html;profile=mcp-app' not null,
    text            clob
);

/*
 * Extend UC_AI_TOOLS to have resource _meta data and output_schema.
 */
create table oj_mcp_tools_extras (
    tool_id       number not null, 
    resource_id   number,
    output_schema clob,
    constraint oj_mcp_tools_extras_pk primary key ("TOOL_ID")
);

alter table oj_mcp_tools_extras add constraint oj_mcp_tools_extras_tool_id_fk foreign key ("TOOL_ID")
references uc_ai_tools ("ID") on delete cascade enable;

alter table oj_mcp_tools_extras add constraint oj_mcp_tools_extras_resource_id_fk foreign key ("RESOURCE_ID")
references oj_mcp_app_resources ("ID") on delete cascade enable;

/*
 * Add definitions for resources and output_schema to UC_AI_TOOLS.
 */
create or replace view oj_mcp_uc_ai_tools as
select
    t.id                   id,
    t.code                 code,
    t.description          description,
    t.active               active,
    t.response_schema      response_schema,
    t.version              version,
    t.function_call        function_call,
    t.authorization_schema authorization_chema,
    t.created_by           created_by,
    t.created_at           created_at,
    t.updated_by           updated_by,
    t.updated_at           updated_at,
    e.resource_id          resource_id,
    e.output_schema        output_schema
from
    uc_ai_tools t left outer join oj_mcp_tools_extras e
    on t.id = e.tool_id
;
