server {
        listen       443 ssl;
        listen       [::]:443 ssl;
        # comment out if nginx < 1.26
        http2        off;
        server_name  ords.example.com;
        root         /usr/share/nginx/html;

        ssl_certificate "/etc/letsencrypt/live/ords.example.com/fullchain.pem";
        ssl_certificate_key "/etc/letsencrypt/live/ords.example.com/privkey.pem";

        ssl_protocols TLSv1.2 TLSv1.3;
        # comment out if nginx < 1.26 and OpenResty
        #ssl_ciphers PROFILE=SYSTEM;
        ssl_prefer_server_ciphers on;

        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout  1d;
        ssl_session_tickets  off;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
}
