location /.well-known/ {
    # Apply CORS headers for all methods
    more_set_headers "Access-Control-Allow-Origin: *";
    more_set_headers "Access-Control-Allow-Methods: GET, OPTIONS";
    more_set_headers "Access-Control-Allow-Headers: Content-Type, Authorization, mcp-protocol-version, mcp-session-id, Accept, Accept-Language";
    more_set_headers "Access-Control-Max-Age: 600";
    more_set_headers "Access-Control-Expose-Headers: Mcp-Session-Id, MCP-Protocol-Version";
    more_set_headers "MCP-Protocol-Version: $http_mcp_protocol_version";

    # OPTIONS preflight
    if ($request_method = OPTIONS) {
        add_header Content-Length 0 always;
        return 204;
    }

    # GET
    alias /usr/share/nginx/html/.well-known/;
    default_type application/json;
    add_header Cache-Control "no-store" always;
}

location @ords_401 {
    internal;
    more_clear_headers 'WWW-Authenticate';
    # The same IdP is used for all MCP servers.
    add_header WWW-Authenticate 'Bearer resource_metadata="$scheme://$host/.well-known/oauth-protected-resource"' always;
    # Scope for Microsoft Entra ID
    #add_header WWW-Authenticate 'Bearer resource_metadata="$scheme://$host/.well-known/oauth-protected-resource",scope="api://58e228b1-9a4b-4dcc-8957-06e3f4ee9081/mcp:connect"' always;
    # Dedicated IdP is assigned to each MCP server.
    #add_header WWW-Authenticate 'Bearer resource_metadata="$scheme://$host/.well-known/oauth-protected-resource$uri"' always;

    # CORS Headers
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, POST, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Content-Type, Authorization, mcp-protocol-version, Accept, Accept-Language" always;
    add_header Cache-Control "no-store" always;
    add_header Access-Control-Expose-Headers "MCP-Protocol-Version" always;
    add_header MCP-Protocol-Version $http_mcp_protocol_version always; # MCP Protocol Version

    return 401;
}