# nginx.conf for OpenResty.
# remove module import from nginx.conf.
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /usr/local/openresty/nginx/logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    log_format extended '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       'referer:"$http_referer" '
                       'ua:"$http_user_agent" '
                       'content-type:"$http_content_type" '
                       'authorization:"$http_authorization" '
                       'mcp-protocol-version:"$http_mcp_protocol_version"';
                       
    log_format bodylog '$remote_addr $time_local '
                       '"$request" '
                       'body:$request_body';

    access_log  /var/log/nginx/access.log  main;
    #access_log   /var/log/nginx/extended.log extended;
    #access_log   /var/log/nginx/body.log body;

    sendfile            on;
    #tcp_nopush          on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;
}
