/* -----------------------------------------------------------------------------
 * ORDS REST servcie 'sampleserver' that implements MCP Server with get_schema and run_sql.
 * -----------------------------------------------------------------------------
 */
-- Generated by ORDS REST Data Services 25.1.0.r1001652
-- Schema: WKSP_APEXDEV  Date: 火 5月  27 08:00:03 2025 
--
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;
  l_workspace_id number;
  l_exist     pls_integer;
BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sampleserver',
      p_base_path      => '/sampleserver/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sampleserver',
      p_pattern        => 'mcp',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sampleserver',
      p_pattern        => 'mcp',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'declare
    l_response    blob;
    l_session_id  varchar2(128);
    l_status_code number;
    l_request     blob;
begin
    l_request := :body;
    oj_mcp_app_server.ords_handler(
        p_script_name  => owa_util.get_cgi_env(''SCRIPT_NAME'') || owa_util.get_cgi_env(''PATH_INFO'') 
        ,p_username    => :current_user
        ,p_request     => l_request
        ,p_response    => l_response
        ,p_session_id  => l_session_id
        ,p_status_code => l_status_code
    );
    /*
     * Return the response to the caller.
     */
    :status_code := l_status_code;
    sys.htp.init;
    sys.htp.p(''Content-Type: application/json'');
    if l_session_id is not null then
        sys.htp.p(''Mcp-Session-Id: '' || l_session_id);
    end if;
    if l_response is not null and dbms_lob.getlength(l_response) > 0 then
        sys.htp.p(''Content-Length: '' || dbms_lob.getlength(l_response));
        sys.owa_util.http_header_close;
        sys.wpg_docload.download_file(l_response);
    else
        sys.owa_util.http_header_clo' || 'se;
    end if;
    commit;
end;');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sampleserver',
      p_pattern        => 'mcp',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
    l_session_id varchar2(128);
begin
    l_session_id := owa_util.get_cgi_env(''Mcp-Session-Id'');
    if l_session_id is not null then
        apex_session.delete_session(l_session_id);
    end if;
    :status_code := 204;
end;');

    
  ORDS.CREATE_ROLE(p_role_name => 'ORDSUsers');
    
  l_roles(1) := 'ORDSUsers';
  l_modules(1) := 'sampleserver';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.example.mcp',
      p_roles          => l_roles,
      p_patterns       => l_patterns, -- no assignment
      p_modules        => l_modules,
      p_label          => 'MCP Server',
      p_description    => NULL,
      p_comments       => NULL);

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
        
COMMIT;

END;
/