create table oj_mcp_ras_sessions (
    id                number generated by default on null as identity
                      constraint oj_mcp_ras_sessions_id_pk primary key,
    mcp_session_id    varchar2(128 char),
    username          varchar2(128 char) not null,
    ras_session_id    raw(16) not null,
    status            varchar2(16 char) constraint oj_mcp_ras_sessions_status_ck
                      check (status in ('CREATED','ATTACHED','DETACHED','DESTROYED')),
    created_at        timestamp not null,
    updated_at        timestamp not null
);
